export const ENV = {
    COGNITO_REGION: 'COGNITO_REGION',
    COGNITO_USER_POOL_ID: 'COGNITO_USER_POOL_ID',
    COGNITO_APP_CLIENT_ID: 'COGNITO_APP_CLIENT_ID',
    COGNITO_IDENTITY_POOL_ID: 'COGNITO_IDENTITY_POOL_ID',

    URI: {
        uri1: 'uri1'
    }
}
