/**
 * action type dictionary
 */

// EXAMPLE
export const EXAMPLE_COUNTER_DECREMENT = 'EXAMPLE_COUNTER_DECREMENT'
export const EXAMPLE_COUNTER_INCREMENT = 'EXAMPLE_COUNTER_INCREMENT'
export const EXAMPLE_TODOS_ADD_NEW = 'EXAMPLE_TODOS_ADD_NEW'
export const EXAMPLE_TODOS_TOGGLE = 'EXAMPLE_TODOS_TOGGLE'
